FROM openjdk:8-jdk

ARG QT_CI_LOGIN
ARG QT_CI_PASSWORD
MAINTAINER Angelo Mantellini <manangel@cisco.com>

ENV VERBOSE=1

RUN apt update && apt -y install build-essential libdbus-1-3 libgl1-mesa-glx libglib2.0-0 jq

RUN apt-get clean

RUN git clone https://github.com/icn-team/android-sdk.git && cd android-sdk && make init_sdk \
  && export QT_CI_LOGIN=${QT_CI_LOGIN} \
  && export QT_CI_PASSWORD=${QT_CI_PASSWORD} \
  && make install-env \
  && rm -rf qt/qt-opensource-* \
  && rm -rf qt/qtci \
  && rm -rf sdk/sdk-tools-* \
  && cd .. \
  && mv android-sdk/sdk . \
  && mv android-sdk/qt . \
  && rm -rf android-sdk
