 #############################################################################
 # Copyright (c) 2022 Cisco and/or its affiliates.
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
 # You may obtain a copy of the License at:
 #
 #     http://www.apache.org/licenses/LICENSE-2.0
 #
 # Unless required by applicable law or agreed to in writing, software
 # distributed under the License is distributed on an "AS IS" BASIS,
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
 ##############################################################################

ARG BASE_IMAGE=ubuntu:22.04
FROM $BASE_IMAGE

MAINTAINER Angelo Mantellini <manangel@cisco.com>

ARG GITHUB_USERNAME
ARG GITHUB_PASSWORD
ARG GITHUB_MVN_REPO
ARG VERSION
ENV A_USERNAME=$GITHUB_USERNAME
ENV A_PASSWORD=$GITHUB_PASSWORD
ENV GITHUB_MVN_REPO=$GITHUB_MVN_REPO
ENV VERSION=$VERSION

COPY . /android-sdk

WORKDIR /android-sdk

RUN gradle --version
RUN echo sdk.dir=`pwd`/sdk > CommonLibrary/local.properties && cd CommonLibrary && gradle compileReleaseSources
RUN make android_facemgrlibraryaar
RUN make android_forwarderlibraryaar